------------------------------------ CUSTOMER ------------------------------------

DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER (
    ID          BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    IDCARD      VARCHAR(50) NOT NULL,
    "NAME"      VARCHAR(50) NOT NULL,
    ADDRESS     VARCHAR(50) NOT NULL,
    TELEPHONE   VARCHAR(50) NOT NULL,
    EMAIL       VARCHAR(50) NOT NULL
 );

INSERT INTO CUSTOMER (IDCARD, NAME, ADDRESS, TELEPHONE, EMAIL)
VALUES ('idCard01', 'Petr01', 'Ceska 01', '123-466-789-01', 'xxx@yyy.01');
INSERT INTO CUSTOMER (IDCARD, NAME, ADDRESS, TELEPHONE, EMAIL)
VALUES ('idCard02', 'Petr02', 'Ceska 02', '123-466-789-02', 'xxx@yyy.02');
INSERT INTO CUSTOMER (IDCARD, NAME, ADDRESS, TELEPHONE, EMAIL)
VALUES ('idCard03', 'Petr03', 'Ceska 03', '123-466-789-03', 'xxx@yyy.03');

------------------------------------ BOOK ------------------------------------

DROP TABLE BOOK;

CREATE TABLE BOOK (
    ID            INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ISBN          VARCHAR(50) NOT NULL,
    "NAME"        VARCHAR(50) NOT NULL,
    AUTHOR        VARCHAR(50) NOT NULL,
    PUBLISHER     VARCHAR(50) NOT NULL,
    "YEAR"        INTEGER NOT NULL,
    LANGUAGE      VARCHAR(50) NOT NULL,
    PAGESNUMBER   INTEGER NOT NULL
 );

INSERT INTO BOOK (ISBN, NAME, AUTHOR, PUBLISHER, "YEAR", LANGUAGE, PAGESNUMBER)
VALUES ('123456-01', 'TestBook.01', 'TestAuthor.01', 'Unknown-01', 1901, 'English', 251);
INSERT INTO BOOK (ISBN, NAME, AUTHOR, PUBLISHER, "YEAR", LANGUAGE, PAGESNUMBER)
VALUES ('123456-02', 'TestBook.02', 'TestAuthor.02', 'Unknown-02', 1902, 'English', 252);
INSERT INTO BOOK (ISBN, NAME, AUTHOR, PUBLISHER, "YEAR", LANGUAGE, PAGESNUMBER)
VALUES ('123456-03', 'TestBook.03', 'TestAuthor.03', 'Unknown-03', 1903, 'English', 253);