CREATE TABLE LOAN (
  ID            BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  IDCUSTOMER    BIGINT NOT NULL REFERENCES CUSTOMER(ID) ON DELETE CASCADE,
  IDBOOK        BIGINT NOT NULL REFERENCES BOOK(ID) ON DELETE CASCADE,
  STARTDATE     DATE NOT NULL,
  ENDDATE       DATE NOT NULL,
  REALENDDATE   DATE,

  CONSTRAINT CHK_END_DATE CHECK (ENDDATE >= STARTDATE),
  CONSTRAINT CHK_REAL_END_DATE CHECK (REALENDDATE >= STARTDATE)
);