CREATE TABLE CUSTOMER (
  ID          BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  IDCARD      VARCHAR(255) NOT NULL,
  "NAME"      VARCHAR(255) NOT NULL,
  ADDRESS     VARCHAR(255) NOT NULL,
  TELEPHONE   VARCHAR(255) NOT NULL,
  EMAIL       VARCHAR(255) NOT NULL
);