CREATE TABLE BOOK (
  ID            BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  ISBN          VARCHAR(20) NOT NULL,
  "NAME"        VARCHAR(255) NOT NULL,
  AUTHOR        VARCHAR(255) NOT NULL,
  PUBLISHER     VARCHAR(255) NOT NULL,
  "YEAR"        INTEGER NOT NULL,
  "LANGUAGE"    VARCHAR(255) NOT NULL,
  PAGESNUMBER   INTEGER NOT NULL,

  CONSTRAINT CHK_PAGESNUMBER CHECK (PAGESNUMBER > 0)
);