CREATE TABLE LOAN (
  ID            BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  IDCUSTOMER    BIGINT NOT NULL,
  IDBOOK        BIGINT NOT NULL,
  STARTDATE     VARCHAR(50) NOT NULL,
  ENDDATE       VARCHAR(50) NOT NULL,
  REALENDDATE   VARCHAR(50)
);