------------------------------------ CUSTOMER ------------------------------------

CREATE TABLE CUSTOMER (
  ID          BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  IDCARD      VARCHAR(50) NOT NULL,
  "NAME"      VARCHAR(50) NOT NULL,
  ADDRESS     VARCHAR(50) NOT NULL,
  TELEPHONE   VARCHAR(50) NOT NULL,
  EMAIL       VARCHAR(50) NOT NULL
);

------------------------------------ BOOK ------------------------------------

CREATE TABLE BOOK (
  ID            BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  ISBN          VARCHAR(50) NOT NULL,
  "NAME"        VARCHAR(50) NOT NULL,
  AUTHOR        VARCHAR(50) NOT NULL,
  PUBLISHER     VARCHAR(50) NOT NULL,
  "YEAR"        INTEGER NOT NULL,
  "LANGUAGE"    VARCHAR(50) NOT NULL,
  PAGESNUMBER   INTEGER NOT NULL
);

------------------------------------ LOAN ------------------------------------

CREATE TABLE LOAN (
  ID            BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  IDCUSTOMER    BIGINT NOT NULL,
  IDBOOK        BIGINT NOT NULL,
  STARTDATE     VARCHAR(50) NOT NULL,
  ENDDATE       VARCHAR(50) NOT NULL,
  REALENDDATE   VARCHAR(50)
);